version: '3.8'

services:
  koenbot:
    build: .
    container_name: koenbot
    restart: always
    volumes:
      - ./store:/botapp/store
      - ./temp:/botapp/temp
    tty: true                   